### ISSUE TITLE
Implement RTP Form Design

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#140]
Our talented designers have come up with a form design that is now ready to implement. 

https://miro.com/app/board/uXjVOY6rC94=/

**Comment by elliottSlee** [comment]
Would you like me to refine this to individual user stories:
- [ ] As a user, I want to be able to find help while completing the form where I usually expect it in the navbar.
- [ ] As a program administrator, I want my users to know they are on the correct page for "Connected Communities BC".
- [ ] As a user, I want to be able to logout and return later.
- [ ] As a returning user, I want to know what I last worked on so I can orient myself when I return.
...

**Comment by BryanGK** [comment]
Yes, please. Each of those is an individual story with their own definitions of done. Usually the format is:

As a \<user type\>
I want to \<what\>
So that I can <why's this important>

DoD:
- [ ] thing to complete to get closer to done
- [ ] next thing to be done.

**Comment by rgreensp** [comment]
Epic - should have stories underneath it.
